/* ------------------------------------------------
* Guess It Game
*
* Class: CS 141, Fall 2017.  Tues 9am lab
* System: Windows 10, Visual Studio Community 2017
* Author: Phillip Sopt
* TA:  Moumita Samanta
*
* Description: This program is designed as a game to guess the users character that they pick from the table.
* -------------------------------------------------
*/

#include<iostream>
#include<ctime>
#include<stdlib.h>
#include<iomanip>

using namespace std;

char GenerateLetter(int,char &);

int main() {
	//Display the Header
	cout << "Program #1: Guess It" << endl;
	cout << "Author : Phillip Sopt" << endl;
	cout << "Lab : Tues 9am" << endl;
	cout << "TA : Moumita Samanta" << endl;
	cout << "Date : Sep 2, 2017" << endl;
	cout << "System : C++ in Visual Studio Community 2017" << endl;
	cout << endl << endl;

	srand(time(0));//choose a seed based on the time for randomness every time the program is run
	const int TABLE_ROWS = 10;//some const int to avoid hard code in the for loops
	const int TABLE_COLUMNS = 10;
	int numTableIndex;//stores the index for moving through the table
	char charAnswer;//stores the answer for the end

	while (true) {//infinite while loop so the user can play as much as his heart desires

		numTableIndex = 99;//init the index to 99
		charAnswer = ' ';//reset the answer to a non alpha (used for later in the GenerateLetter())

		for (int i = 0; i < TABLE_ROWS; i++)//for loop to iterate through the table rows
		{
			for (int j = 0; j < TABLE_COLUMNS; j++)//for loop used to iterate through the table columns
			{
				//setw to make the table spacing nice
				cout << setw(4) << numTableIndex << ":" << GenerateLetter(numTableIndex, charAnswer);//print out the index along with a letter generated by the GenerateLetter() ex. 99:a
				numTableIndex--;//decrement the index
			}
			cout << endl;//after the for loop is done with the first column then make a new line

		}

		cout << endl << endl;//Display the instructions
		cout << "1. Choose any two - digit number in the table above(e.g. 73)." << endl;
		cout << "2. Subtract its two digits from itself(e.g. 73 - 7 - 3 = 63)" << endl;
		cout << "3. Find this new number(e.g. 63) and remember the letter next to it." << endl;
		cout << "4. Now press 'r' and I'll read your mind..." << endl;
		cout << endl;

		char userInput = '-';
		while (userInput != 'r')
		{
			cin >> userInput;
			cout << "Please press 'r' for the answer." << endl;
		}
		cout << "Your answer is: " << charAnswer << endl;
		system("pause");//wait until they press enter again
		cout << "==================================" << endl;
	}
	
	


	return 0;
}


char GenerateLetter(int index, char &answer)//used to generate a random letter and return it. It takes the parameters tableIndex, and the current answer
{
	char result = rand() % 26 + 97;//generate a random char

	if (index % 2 == 0 && (rand() % 3 == 0))//if the index is even with a 33% chance, the result will be capitalized. Two conditions to add randomness to the letter's casing
	{
		result = toupper(result);
	}

	if (index % 9 == 0)//if the index is a multiple of 9
	{
		if (!isalpha(answer))//check to see if we have an answer already
		{
			answer = result;//set answer to the randomly generated result and because we are using call by reference
		}
		else//if we already have an answer then just set the result to that answer
		{
			result = answer;
		}
		
	}

	return result;//return the result back to the main
}
